# helm/gpu-lotto/templates/price-watcher/service.yaml
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-lotto.fullname" . }}-price-watcher
  namespace: {{ include "gpu-lotto.namespace" . }}
  labels:
    {{- include "gpu-lotto.labels" . | nindent 4 }}
    app.kubernetes.io/name: price-watcher
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: price-watcher
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
{{- end }}
