# helm/gpu-lotto/templates/api-server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.serviceAccount.name }}
  namespace: {{ include "gpu-lotto.namespace" . }}
  labels:
    {{- include "gpu-lotto.labels" . | nindent 4 }}
  {{- with .Values.apiServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
