# helm/gpu-lotto/templates/dispatcher/pdb.yaml
{{- if .Values.dispatcher.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gpu-lotto.fullname" . }}-dispatcher
  namespace: {{ include "gpu-lotto.namespace" . }}
  labels:
    {{- include "gpu-lotto.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.dispatcher.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dispatcher
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
